import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
const require = createRequire(resolve('/tmp/yaml-test', 'package.json'));
const yaml = require('yaml');
const configPath = '/tmp/yaml-test/config.yaml';
writeFileSync(configPath, '{"llm":{}, "embedding":{}}');
const provider = 'ollama';
const endpoint = 'http://test:11434';
const llmModel = 'my-llama';
const embedModel = 'my-embed';
const doc = yaml.parseDocument(readFileSync(configPath, 'utf8'));
doc.setIn(['llm', 'baseUrl'], endpoint || 'http://127.0.0.1:11434');
doc.setIn(['llm', 'model'], llmModel || 'llama3');
doc.setIn(['memory', 'embedding', 'provider'], 'ollama');
doc.setIn(['memory', 'embedding', 'baseUrl'], endpoint || 'http://127.0.0.1:11434');
doc.setIn(['memory', 'embedding', 'model'], embedModel || 'nomic-embed-text');
console.log(String(doc));
