import assert from 'node:assert/strict';
import { test } from 'node:test';
import http from 'node:http';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { AddressInfo } from 'node:net';
import { WebSocket } from 'ws';
import type { PairingOffer, PairingPreview, PairedDevice } from '@git-agent-harness/contracts';
import { DeviceAccess, DEVICE_COOKIE } from './deviceAccess.js';
import { createServer } from './server.js';
import { createAuthorizedWebSocketServer, webSocketAccessValid } from './webSocketAuth.js';
import { resetCachedCoordinatorIdentity } from './coordinatorIdentity.js';

test('real HTTP/WS pairing confirms access, rejects CSRF and owner exports, and revokes existing sockets individually', async () => {
  const directory = mkdtempSync(join(tmpdir(), 'gah-pairing-http-'));
  const keys = ['COORDINATOR_TOKEN', 'GAH_ALLOW_INSECURE_HTTP', 'GAH_COORDINATOR_IDENTITY_PATH', 'GAH_WS_AUTH_MODE'] as const;
  const saved = keys.map(key => process.env[key]);
  process.env.COORDINATOR_TOKEN = 'owner-secret-never-in-qr';
  process.env.GAH_ALLOW_INSECURE_HTTP = '1';
  process.env.GAH_COORDINATOR_IDENTITY_PATH = join(directory, 'identity.json');
  process.env.GAH_WS_AUTH_MODE = 'trusted_lan';
  resetCachedCoordinatorIdentity();
  const access = new DeviceAccess(join(directory, 'devices.json'));
  const server = http.createServer(createServer({ deviceAccess: access }));
  const wss = createAuthorizedWebSocketServer(server, 'central', access);
  let messages = 0;
  let deviceSocket: WebSocket | undefined;
  wss.on('connection', ws => {
    deviceSocket = ws;
    ws.on('message', () => { if (webSocketAccessValid(ws)) messages++; });
  });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const remote = { 'X-Forwarded-For': '198.51.100.2', Origin: base };
  const owner = { ...remote, Authorization: 'Bearer owner-secret-never-in-qr' };
  const post = (path: string, body: unknown, headers: Record<string, string> = remote) => fetch(base + path, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const connect = (cookie: string, origin = base): Promise<WebSocket | number> => new Promise((resolve, reject) => {
    const socket = new WebSocket(base.replace('http:', 'ws:') + '/ws', ['gah.v1'], { headers: { ...remote, Origin: origin, Cookie: cookie } });
    socket.once('open', () => resolve(socket));
    socket.once('unexpected-response', (_req, res) => { res.resume(); resolve(res.statusCode!); });
    socket.once('error', reject);
  });
  try {
    assert.equal((await post('/api/pairing/offers', { origin: base })).status, 401);
    const response = await post('/api/pairing/offers', { origin: base }, owner);
    assert.equal(response.status, 200);
    assert.equal(response.headers.get('cache-control'), 'no-store');
    const offer = await response.json() as PairingOffer;
    assert.ok(!JSON.stringify(offer).includes(process.env.COORDINATOR_TOKEN!));
    const input = { code: offer.code, server_id: offer.server.id };
    assert.equal((await post('/api/pairing/inspect', input, { ...remote, Origin: 'http://attacker.test' })).status, 403);
    assert.equal((await post('/api/pairing/inspect', { ...input, server_id: 'wrong-server' })).status, 400);
    const preview = await post('/api/pairing/inspect', input);
    assert.equal(preview.status, 200);
    assert.match((await preview.json() as PairingPreview).access, /run agent work/);
    assert.equal((await post('/api/pairing/redeem', { ...input, name: 'Phone' })).status, 400);
    const redeemed = await post('/api/pairing/redeem', { ...input, name: 'Phone', confirm: true });
    assert.equal(redeemed.status, 200);
    const setCookie = redeemed.headers.get('set-cookie')!;
    assert.match(setCookie, /HttpOnly/);
    assert.match(setCookie, /SameSite=Strict/);
    assert.ok(!setCookie.includes('Secure'), 'Explicit trusted HTTP must not silently issue an unusable Secure cookie');
    const cookie = setCookie.split(';')[0];
    const result = await redeemed.json() as { device: PairedDevice };
    assert.ok(!JSON.stringify(result).includes(cookie.split('=')[1]));
    assert.equal((await post('/api/pairing/redeem', { ...input, name: 'Replay', confirm: true })).status, 400);
    const paired = { ...remote, Cookie: cookie };
    assert.equal((await fetch(base + '/api/info', { headers: paired })).status, 200);
    assert.equal((await fetch(base + '/api/info', { headers: { Cookie: cookie, 'Sec-Fetch-Site': 'same-origin' } })).status, 200, 'Same-origin browser GETs may omit Origin');
    assert.equal((await fetch(base + '/api/info', { headers: { Cookie: cookie } })).status, 401, 'Cookie access without browser origin evidence is denied');
    assert.equal((await fetch(base + '/api/info', { headers: { ...paired, Origin: 'http://attacker.test' } })).status, 401);
    assert.equal((await post('/api/pairing/offers', { origin: base }, paired)).status, 403);
    assert.equal((await post('/api/settings/nodes/command', { centralUrl: base, role: 'desktop' }, paired)).status, 403);
    assert.equal((await post('/api/settings/gateway/bootstrap-command', {}, paired)).status, 403);
    assert.equal((await fetch(base + '/api/info', { headers: { ...paired, Cookie: `${cookie}; ${cookie}` } })).status, 401);
    assert.equal(await connect(cookie, 'http://attacker.test'), 403);
    const socket = await connect(cookie);
    assert.ok(socket instanceof WebSocket);
    socket.send('test');
    await new Promise<void>(resolve => deviceSocket!.once('message', () => resolve()));
    assert.equal(messages, 1);
    const closed = new Promise<void>(resolve => socket.once('close', () => resolve()));
    assert.equal((await fetch(`${base}/api/pairing/devices/${result.device.id}`, { method: 'DELETE', headers: owner })).status, 200);
    await closed;
    assert.equal(webSocketAccessValid(deviceSocket!), false);
    assert.equal((await fetch(base + '/api/info', { headers: paired })).status, 401);
    assert.equal(await connect(cookie), 401, 'A revoked cookie cannot downgrade into trusted-LAN mode');
    assert.equal((await fetch(base + '/api/info', { headers: { Cookie: cookie, Origin: base } })).status, 401, 'Local trust cannot rescue revoked supplied credentials');
    const logout = await post('/api/pairing/logout', {}, paired);
    assert.equal(logout.status, 200);
    assert.match(logout.headers.get('set-cookie')!, new RegExp(`${DEVICE_COOKIE}=;`));
    // TLS proxy transport sets a Secure cookie; disabling HTTP prevents insecure offers.
    delete process.env.GAH_ALLOW_INSECURE_HTTP;
    assert.equal((await post('/api/pairing/offers', { origin: base }, owner)).status, 403);
    const tlsOrigin = base.replace('http:', 'https:');
    const tlsHeaders = { ...remote, Origin: tlsOrigin, 'X-Forwarded-Proto': 'https' };
    const tlsOffer = await (await post('/api/pairing/offers', { origin: tlsOrigin }, { ...tlsHeaders, Authorization: 'Bearer owner-secret-never-in-qr' })).json() as PairingOffer;
    const tlsResult = await post('/api/pairing/redeem', { code: tlsOffer.code, server_id: tlsOffer.server.id, name: 'Secure phone', confirm: true }, tlsHeaders);
    assert.equal(tlsResult.status, 200);
    assert.match(tlsResult.headers.get('set-cookie')!, /; Secure/);
    assert.equal((await post('/api/pairing/offers', { origin: 'https://unconfigured.example.test' }, { ...tlsHeaders, Authorization: 'Bearer owner-secret-never-in-qr' })).status, 400);
    for (let i = 0; i < 35; i++) await post('/api/pairing/inspect', input, tlsHeaders);
    assert.equal((await post('/api/pairing/inspect', input, tlsHeaders)).status, 429);
  } finally {
    for (const socket of wss.clients) socket.terminate();
    await new Promise<void>(resolve => wss.close(() => resolve()));
    await new Promise<void>(resolve => server.close(() => resolve()));
    keys.forEach((key, index) => { if (saved[index] === undefined) delete process.env[key]; else process.env[key] = saved[index]; });
    resetCachedCoordinatorIdentity();
    rmSync(directory, { recursive: true, force: true });
  }
});
