import assert from 'node:assert/strict';
import { test } from 'node:test';
import http from 'node:http';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { AddressInfo } from 'node:net';
import { WebSocket } from 'ws';
import type { PairingAccessRequest, ActivityEvent } from '@git-agent-harness/contracts';
import { DeviceAccess, DEVICE_COOKIE, PAIRING_REQUEST_COOKIE } from './deviceAccess.js';
import { createServer } from './server.js';
import { createAuthorizedWebSocketServer } from './webSocketAuth.js';
import { sessionStore } from './wsServer.js';
import { ActivityFeed } from './activityFeed.js';
import { resetCachedCoordinatorIdentity } from './coordinatorIdentity.js';
import { RegistryService } from './registryService.js';
import { FIXTURE_GAH_BINARY } from './fixtureGahHarness.js';

test('trusted-device sign-in binds approval to the requesting browser and only grants controller access', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'gah-approval-http-'));
  const keys = ['COORDINATOR_TOKEN', 'GAH_ALLOW_INSECURE_HTTP', 'GAH_COORDINATOR_IDENTITY_PATH', 'GAH_WS_AUTH_MODE', 'GAH_SKILL_BANK_PATH',
    'GAH_GATEWAY_SETTINGS_PATH', 'GAH_MANAGER_CHAT_SETTINGS_PATH', 'GAH_BINARY', 'GAH_FIXTURE_PROFILE_LIST'] as const;
  const saved = keys.map(key => process.env[key]);
  process.env.COORDINATOR_TOKEN = 'owner-fixture-secret';
  delete process.env.GAH_ALLOW_INSECURE_HTTP;
  delete process.env.GAH_WS_AUTH_MODE;
  process.env.GAH_COORDINATOR_IDENTITY_PATH = join(directory, 'identity.json');
  process.env.GAH_SKILL_BANK_PATH = join(directory, 'skills.json');
  process.env.GAH_GATEWAY_SETTINGS_PATH = join(directory, 'gateway.json');
  process.env.GAH_MANAGER_CHAT_SETTINGS_PATH = join(directory, 'chat.json');
  process.env.GAH_BINARY = FIXTURE_GAH_BINARY;
  process.env.GAH_FIXTURE_PROFILE_LIST = join(directory, 'profiles.json');
  writeFileSync(process.env.GAH_FIXTURE_PROFILE_LIST, '[]');
  resetCachedCoordinatorIdentity();
  let now = Date.now();
  const access = new DeviceAccess(join(directory, 'devices.json'), () => now);
  const feed = new ActivityFeed(join(directory, 'activity.jsonl'));
  feed.onChange(change => { if (change.kind === 'unread') sessionStore.broadcastUnread(feed); });
  const server = http.createServer(createServer({ deviceAccess: access, activityFeed: feed,
    registryService: new RegistryService(join(directory, 'registry.json')), detectTailscaleIPv4: async () => null }));
  const wss = createAuthorizedWebSocketServer(server, 'central', access, () => now);
  wss.on('connection', ws => {
    sessionStore.add(ws, 'fixture', { version: 'fixture', supportsTerminal: false, supportsNotifications: true }, 'fixture');
    ws.once('close', () => sessionStore.remove(ws));
  });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const origin = base.replace('http:', 'https:');
  const remote = { 'X-Forwarded-For': '198.51.100.2', 'X-Forwarded-Proto': 'https', Origin: origin };
  const owner = { ...remote, Authorization: 'Bearer owner-fixture-secret' };
  const send = (path: string, method: string, body: object | undefined, headers: Record<string, string> = remote) => fetch(base + '/api/pairing' + path,
    { method, headers: { ...headers, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const post = (path: string, body: object, headers: Record<string, string> = remote) => send(path, 'POST', body, headers);
  const get = (path: string, headers: Record<string, string> = remote) => send(path, 'GET', undefined, headers);
  const sockets: WebSocket[] = [];
  const connect = (headers: Record<string, string>): Promise<WebSocket | number> => new Promise((resolve, reject) => {
    const socket = new WebSocket(base.replace('http:', 'ws:') + '/ws', ['gah.v1'], { headers });
    socket.once('open', () => { sockets.push(socket); resolve(socket); });
    socket.once('unexpected-response', (_req, res) => { res.resume(); resolve(res.statusCode!); });
    socket.once('error', reject);
  });
  t.after(async () => {
    for (const socket of sockets) socket.terminate();
    await new Promise<void>(resolve => wss.close(() => resolve()));
    await new Promise<void>(resolve => server.close(() => resolve()));
    keys.forEach((key, index) => { if (saved[index] === undefined) delete process.env[key]; else process.env[key] = saved[index]; });
    resetCachedCoordinatorIdentity();
    rmSync(directory, { recursive: true, force: true });
  });
  const offerServer = { id: 'fixture', name: 'Central', origin };
  const pair = (name: string) => {
    const offer = access.create(offerServer);
    return access.redeem(offer.code, offerServer.id, origin, name);
  };
  const phone = pair('Phone');
  const ordinary = pair('Ordinary controller');
  const phoneHeaders = { ...remote, Cookie: `${DEVICE_COOKIE}=${phone.token}` };
  const ordinaryHeaders = { ...remote, Cookie: `${DEVICE_COOKIE}=${ordinary.token}` };
  assert.equal((await get('/access/requests')).status, 401);
  assert.equal((await get('/access/requests', phoneHeaders)).status, 403);
  assert.equal((await send(`/devices/${phone.device.id}`, 'PATCH', { can_approve_pairing: true }, ordinaryHeaders)).status, 403);
  assert.equal((await send(`/devices/${phone.device.id}`, 'PATCH', { can_approve_pairing: 'true' }, owner)).status, 400);
  assert.equal((await send(`/devices/${phone.device.id}`, 'PATCH', { can_approve_pairing: true }, owner)).status, 200);
  assert.equal((await (await get('/session', phoneHeaders)).json() as { can_approve_pairing: boolean }).can_approve_pairing, true);
  assert.equal((await post('/access/request', { name: 'Linux' }, { ...remote, Origin: 'https://attacker.test' })).status, 403);
  assert.equal((await post('/access/request', { name: 'Linux' }, { ...remote, 'X-Forwarded-Proto': 'http', Origin: base })).status, 403);
  const connected = await Promise.all([connect(owner), connect(phoneHeaders), connect(ordinaryHeaders)]);
  for (const socket of connected) assert.ok(socket instanceof WebSocket);
  const received: ActivityEvent[][] = connected.map(() => []);
  const counts: number[][] = connected.map(() => []);
  connected.forEach((socket, index) => {
    if (socket instanceof WebSocket) socket.on('message', data => {
      const message = JSON.parse(data.toString());
      if (message.type === 'activity.event') received[index].push(message.event);
      if (message.type === 'activity.unread') counts[index].push(message.count);
    });
  });
  const response = await post('/access/request', { name: 'Linux laptop' });
  assert.equal(response.status, 202);
  const requested = await response.json() as PairingAccessRequest;
  const setCookie = response.headers.getSetCookie()[0];
  assert.match(setCookie, /HttpOnly/);
  assert.match(setCookie, /Secure/);
  assert.match(setCookie, /SameSite=Strict/);
  const cookie = setCookie.split(';')[0];
  const requester = { ...remote, Cookie: cookie };
  const otherResponse = await post('/access/request', { name: 'Other laptop' });
  const otherCookie = otherResponse.headers.getSetCookie()[0].split(';')[0];
  const wrongSecret = `${PAIRING_REQUEST_COOKIE}=${requested.id}.${otherCookie.split('.').at(-1)}`;
  assert.equal((await get('/access/status')).status, 404);
  assert.equal((await get('/access/status', { ...remote, Cookie: wrongSecret })).status, 404);
  assert.equal((await get('/access/status', { ...remote, Cookie: `${cookie}; ${cookie}` })).status, 404);
  assert.equal((await get('/access/status', { ...requester, Origin: 'https://attacker.test' })).status, 403);
  assert.equal((await connect(requester)), 401, 'The request cookie never authorizes WebSockets');
  assert.equal((await post('/access/claim', { confirm: true }, requester)).status, 400);
  for (let poll = 0; poll < 35; poll++) assert.equal((await get('/access/status', requester)).status, 200);
  assert.equal((await post(`/access/requests/${requested.id}/approve`, { matching_code: 'FORGED', confirm: true }, phoneHeaders)).status, 409);
  assert.equal((await post(`/access/requests/${requested.id}/approve`, { matching_code: requested.matching_code, confirm: true }, { ...owner, Origin: 'https://attacker.test' })).status, 403);
  assert.equal((await post(`/access/requests/${requested.id}/approve`, { matching_code: requested.matching_code, confirm: true }, phoneHeaders)).status, 200);
  assert.equal((await (await get('/access/status', requester)).json() as PairingAccessRequest).status, 'approved');
  assert.equal((await post('/access/claim', { confirm: false }, requester)).status, 400);
  assert.equal((await post('/access/claim', { confirm: true }, { ...remote, Cookie: wrongSecret })).status, 400);
  const claim = await post('/access/claim', { confirm: true }, requester);
  assert.equal(claim.status, 200);
  const claimed = await claim.json();
  const deviceCookie = claim.headers.getSetCookie().find(value => value.startsWith(`${DEVICE_COOKIE}=`))!.split(';')[0];
  assert.ok(!JSON.stringify(claimed).includes('token'));
  assert.equal((await post('/access/claim', { confirm: true }, requester)).status, 400);
  assert.equal((await get('/session', { ...remote, Cookie: deviceCookie })).status, 200);
  assert.equal((await get('/devices', { ...remote, Cookie: deviceCookie })).status, 403);
  const claimedSocket = await connect({ ...remote, Cookie: deviceCookie });
  assert.ok(claimedSocket instanceof WebSocket);
  assert.equal((await get('/access/requests', { ...remote, Cookie: deviceCookie })).status, 403, 'Approved controller cannot approve another device');
  const task: ActivityEvent = { id: 'task-completed', occurredAt: new Date().toISOString(), profile: null,
    kind: 'dispatch_completed', severity: 'success', title: 'Task finished', message: 'Ready for review.' };
  feed.record(task);
  sessionStore.broadcast({ type: 'activity.event', event: task });
  const inbox = async (headers: Record<string, string>) => (await fetch(base + '/api/activity/notifications', { headers })).json() as Promise<{ events: ActivityEvent[]; unread: number }>;
  assert.deepEqual((await inbox(ordinaryHeaders)).events.map(event => event.id), [task.id]);
  assert.equal((await inbox(ordinaryHeaders)).unread, 1);
  assert.ok((await inbox(phoneHeaders)).events.some(event => event.pairingRequestId === requested.id));
  const markAll = await fetch(base + '/api/activity/read', { method: 'POST', headers: { ...ordinaryHeaders, 'Content-Type': 'application/json' }, body: JSON.stringify({ all: true }) });
  assert.equal((await markAll.json() as { changed: number }).changed, 1, 'A nonapprover cannot acknowledge another device’s approval requests');
  assert.ok((await inbox(owner)).unread > 0);
  assert.equal((await inbox(ordinaryHeaders)).unread, 0);
  assert.equal((await send(`/devices/${phone.device.id}`, 'PATCH', { can_approve_pairing: false }, owner)).status, 200);
  assert.equal((await inbox(phoneHeaders)).unread, 0);
  process.env.GAH_WS_AUTH_MODE = 'trusted_lan';
  const compatibility = await connect(remote);
  assert.ok(compatibility instanceof WebSocket);
  const compatibilityEvents: ActivityEvent[] = [];
  const compatibilityCounts: number[] = [];
  compatibility.on('message', data => {
    const message = JSON.parse(data.toString());
    if (message.type === 'activity.event') compatibilityEvents.push(message.event);
    if (message.type === 'activity.unread') compatibilityCounts.push(message.count);
  });
  const disabledResponse = await post('/access/request', { name: 'After delegation disabled' });
  const disabled = await disabledResponse.json() as PairingAccessRequest;
  assert.equal((await post(`/access/requests/${disabled.id}/approve`, { matching_code: disabled.matching_code, confirm: true }, phoneHeaders)).status, 403);
  assert.deepEqual((await inbox(phoneHeaders)).events.map(event => event.id), [task.id]);
  const expiredResponse = await post('/access/request', { name: 'Expired laptop' });
  const expired = await expiredResponse.json() as PairingAccessRequest;
  const expiredCookie = expiredResponse.headers.getSetCookie()[0].split(';')[0];
  now += 5 * 60_000;
  assert.equal((await (await get('/access/status', { ...remote, Cookie: expiredCookie })).json() as PairingAccessRequest).status, 'expired');
  assert.equal((await post(`/access/requests/${expired.id}/approve`, { matching_code: expired.matching_code, confirm: true }, owner)).status, 409);
  assert.equal((await post('/access/claim', { confirm: true }, { ...remote, Cookie: expiredCookie })).status, 400);
  const events = feed.notifications().filter(event => event.pairingRequestId);
  assert.ok(events.some(event => event.pairingRequestId === requested.id));
  await new Promise<void>(resolve => setImmediate(resolve));
  assert.ok(received[0].some(event => event.pairingRequestId === requested.id));
  assert.ok(received[1].some(event => event.pairingRequestId === requested.id));
  assert.ok(received[0].some(event => event.pairingRequestId === disabled.id));
  assert.ok(!received[1].some(event => event.pairingRequestId === disabled.id), 'Disabling delegation filters sockets already upgraded');
  assert.deepEqual(received[2].map(event => event.id), [task.id], 'Ordinary controller sockets retain task notifications without approval wakes');
  assert.equal(counts[2].at(-1), 0);
  assert.equal(counts[1].at(-1), 0);
  assert.deepEqual(compatibilityEvents, []);
  assert.equal(compatibilityCounts.at(-1), 0);
  const eventDisk = readFileSync(join(directory, 'activity.jsonl'), 'utf8');
  for (const value of [requested.matching_code, cookie.split('.').at(-1)!, 'owner-fixture-secret']) assert.ok(!eventDisk.includes(value));
});
