use crate::config::Profile;
use crate::ledger::LedgerEntry;
use crate::models::ReviewVerdict;
use std::path::Path;

/// TICKET-128: whether the profile may publish the work autonomously. A
/// restricted profile can still run the full backend and validation pipeline
/// and write local artifacts; they just must not be published as an agent-authored MR.
pub(super) fn publishing_allows_publish(profile: &Profile) -> bool {
    profile.publishing.allow_pull_request_creation
        && profile.publishing.allow_commit_message_generation
}

pub(super) fn render_ticket_label(ticket: Option<&crate::dispatch::TicketMetadata>) -> String {
    let Some(ticket) = ticket else {
        return "n/a".into();
    };
    match (ticket.ticket_id.as_deref(), ticket.title.as_deref()) {
        (Some(ticket_id), Some(title)) => format!("{ticket_id} {title}"),
        (Some(ticket_id), None) => ticket_id.to_string(),
        (None, Some(title)) => title.to_string(),
        (None, None) => "n/a".into(),
    }
}

pub(super) fn format_validation_outcome(result: Option<&str>) -> &'static str {
    match result {
        Some("passed") => "passed",
        Some("failed-draft") => "failed, pushed as draft",
        Some("failed") => "failed",
        Some("not_run") => "not run",
        Some("answered") => "answered",
        Some("partial") => "partial",
        Some(_) => "recorded",
        None => "not recorded",
    }
}

pub(super) fn format_failure_state(ledger: &LedgerEntry) -> Option<String> {
    if let Some(summary) = ledger.error_summary.as_deref() {
        let mut state = String::new();
        if let Some(class) = ledger.failure_class.as_deref() {
            state.push_str(&format!("Class: `{class}`\n"));
        }
        if let Some(stage) = ledger.failure_stage.as_deref() {
            state.push_str(&format!("Stage: `{stage}`\n"));
        }
        state.push_str(&format!("Summary: {}", summary.trim()));
        return Some(state);
    }
    if ledger.validation_result.as_deref() == Some("failed-draft") {
        return Some("Validation remained red and the change was pushed as a draft.".into());
    }
    None
}

#[allow(clippy::too_many_arguments)]
pub(super) fn build_standard_mr_body(
    mode: &str,
    ticket: Option<&crate::dispatch::TicketMetadata>,
    backend: &str,
    model: &str,
    _branch: &str,
    _target_branch: &str,
    validation_passed: bool,
    backend_summary: &str,
) -> String {
    let mut sections = vec![format!(
        "## GAH {} mode\n\nTicket: {}\nBackend/model: `{}` / `{}`",
        mode,
        render_ticket_label(ticket),
        backend,
        model,
    )];

    // Add Closes directive for GitHub/GitLab auto-close if this came from an issue
    if let Some(ticket) = ticket {
        if let Some(ref issue_number) = ticket.issue_number {
            sections.push(format!("Closes #{}", issue_number));
        }
    }

    if !backend_summary.is_empty() {
        sections.push(format!("## What changed and why\n\n{}", backend_summary));
    }
    sections.push(format!(
        "Validation passed: {}\n\nGenerated by `gah dispatch`.",
        validation_passed,
    ));
    sections.join("\n\n")
}

pub(super) struct MrRenderContext<'a> {
    pub backend: &'a str,
    pub model: &'a str,
    pub branch: &'a str,
    pub target_branch: &'a str,
    pub validation_commands: &'a [String],
    pub ledger: &'a LedgerEntry,
    pub backend_summary: &'a str,
}

pub(super) fn build_metadata_rich_mr_body(
    mode: &str,
    ticket: &crate::dispatch::TicketMetadata,
    ctx: &MrRenderContext<'_>,
) -> String {
    let mut sections = Vec::new();

    let work_item = match (
        ticket.work_id.as_deref(),
        ticket.ticket_id.as_deref(),
        ticket.title.as_deref(),
    ) {
        (Some(id), _, Some(title)) => Some(format!("ID: `{id}`\nTitle: {title}")),
        (Some(id), _, None) => Some(format!("ID: `{id}`")),
        (None, Some(id), Some(title)) => Some(format!("ID: `{id}`\nTitle: {title}")),
        (None, Some(id), None) => Some(format!("ID: `{id}`")),
        (None, None, Some(title)) => Some(format!("Title: {title}")),
        (None, None, None) => None,
    };
    if let Some(section) = work_item {
        sections.push(format!("## Work Item\n\n{section}"));
    }

    // Add Closes directive for GitHub/GitLab auto-close if this came from an issue
    if let Some(ref issue_number) = ticket.issue_number {
        sections.push(format!("Closes #{}", issue_number));
    }

    if let Some(problem) = ticket.problem.as_deref() {
        sections.push(format!("## Problem\n\n{}", problem.trim()));
    }
    if let Some(goal) = ticket.goal.as_deref() {
        sections.push(format!("## Goal\n\n{}", goal.trim()));
    }
    if !ticket.acceptance_criteria.is_empty() {
        let lines = ticket
            .acceptance_criteria
            .iter()
            .map(|item| format!("- {item}"))
            .collect::<Vec<_>>()
            .join("\n");
        sections.push(format!("## Acceptance Criteria\n\n{lines}"));
    }
    if !ticket.constraints.is_empty() {
        let lines = ticket
            .constraints
            .iter()
            .map(|item| format!("- {item}"))
            .collect::<Vec<_>>()
            .join("\n");
        sections.push(format!("## Constraints\n\n{lines}"));
    }
    if !ctx.backend_summary.is_empty() {
        sections.push(format!(
            "## What changed and why\n\n{}",
            ctx.backend_summary
        ));
    }
    if !ctx.validation_commands.is_empty() || ctx.ledger.validation_result.is_some() {
        let mut lines = vec![format!(
            "Outcome: {}",
            format_validation_outcome(ctx.ledger.validation_result.as_deref())
        )];
        for cmd in ctx.validation_commands {
            lines.push(format!("- `{cmd}`"));
        }
        sections.push(format!("## Validation\n\n{}", lines.join("\n")));
    }

    sections.push(format!(
        "## Backend / Model\n\nBackend: `{}`\nModel: `{}`",
        ctx.backend, ctx.model
    ));
    sections.push(format!(
        "## Attempts\n\nStarted: {}\nCompleted: {}\nFallback used: {}",
        ctx.ledger.attempts_started.unwrap_or(0),
        ctx.ledger.attempts_completed.unwrap_or(0),
        if ctx.ledger.fallback_used {
            "yes"
        } else {
            "no"
        }
    ));

    if let Some(state) = format_failure_state(ctx.ledger) {
        sections.push(format!("## Failure / Stop State\n\n{state}"));
    }

    if let Some(source) = ticket.source.as_deref() {
        sections.push(format!("## Source\n\n{}", source.trim()));
    }

    sections.push(format!("Generated by `gah dispatch --mode {mode}`."));
    sections.join("\n\n")
}

pub(super) fn build_fix_or_improve_mr_body(
    mode: &str,
    ticket: Option<&crate::dispatch::TicketMetadata>,
    ctx: &MrRenderContext<'_>,
    validation_passed: bool,
) -> String {
    match ticket {
        Some(ticket) => build_metadata_rich_mr_body(mode, ticket, ctx),
        None => build_standard_mr_body(
            mode,
            None,
            ctx.backend,
            ctx.model,
            ctx.branch,
            ctx.target_branch,
            validation_passed,
            ctx.backend_summary,
        ),
    }
}

pub(super) struct ExperimentMrRenderContext<'a> {
    pub backend: &'a str,
    pub model: &'a str,
    pub artifact_count: usize,
    pub answered: bool,
    pub backend_summary: &'a str,
}

pub(super) fn build_experiment_mr_body(ctx: &ExperimentMrRenderContext<'_>) -> String {
    let mut sections = vec![
        "## Experiment Result".to_string(),
        format!(
            "\nBackend: `{backend}`\nModel: `{model}`\nJudge verdict: {}\nArtifacts: {}\n",
            if ctx.answered { "answered" } else { "partial" },
            ctx.artifact_count,
            backend = ctx.backend,
            model = ctx.model
        ),
    ];
    if !ctx.backend_summary.is_empty() {
        sections.push(format!(
            "## What changed and why\n\n{}",
            ctx.backend_summary
        ));
    }
    sections.push("Generated by `gah dispatch --mode experiment`.".into());
    sections.join("\n\n")
}

pub(super) fn truncate_title(title: &str, limit: usize) -> String {
    if title.len() <= limit {
        title.to_string()
    } else {
        let mut truncated = String::new();
        let mut char_count = 0;
        for c in title.chars() {
            if char_count < limit - 3 {
                truncated.push(c);
                char_count += 1;
            } else {
                break;
            }
        }
        truncated.push_str("...");
        truncated
    }
}

pub(super) fn build_mr_title(
    mode: &str,
    repo_id: &str,
    validation_failed: bool,
    ticket: Option<&crate::dispatch::TicketMetadata>,
) -> String {
    let mode_label = match mode {
        "fix" => "Fix",
        "improve" => "Improve",
        "review" => "Review",
        "pm" => "Plan",
        other => other,
    };
    let prefix = if validation_failed {
        "[GAH][DRAFT-FAIL]"
    } else {
        "[GAH]"
    };
    let title_string = if let Some(ticket) = ticket {
        let title_text = ticket
            .suggested_mr_title
            .as_deref()
            .or(ticket.title.as_deref());
        if let Some(title) = title_text {
            let detail = if ticket.is_authoritative {
                if let Some(ref work_id) = ticket.work_id {
                    format!("{work_id} {title}")
                } else if let Some(ref ticket_id) = ticket.ticket_id {
                    format!("{ticket_id} {title}")
                } else {
                    title.to_string()
                }
            } else {
                title.to_string()
            };
            format!("{prefix} {mode_label}: {detail}")
        } else {
            format!("{prefix} {mode_label}: {repo_id}")
        }
    } else {
        format!("{prefix} {mode_label}: {repo_id}")
    };
    truncate_title(&title_string, 255)
}

pub(super) fn render_review_comment(verdict: &ReviewVerdict, session_dir: &Path) -> String {
    let published = &verdict.verdict;
    let mut out = format!(
        "GAH review verdict: `{}`\n\nConfidence: `{}`\nHuman required: `{}`\nReviewer: `{}` / `{}`\nArtifacts: `{}`\n",
        published,
        verdict.confidence,
        verdict.human_required,
        verdict.effective_backend.as_deref().unwrap_or("unknown"),
        verdict.effective_model.as_deref().unwrap_or("unknown"),
        session_dir.display(),
    );
    if !verdict.blocking_findings.is_empty() {
        out.push_str("\nBlocking findings:\n");
        for item in &verdict.blocking_findings {
            out.push_str(&format!("- {}\n", item));
        }
    }
    // A verdict with zero blocking findings (e.g. a low-confidence APPROVE)
    // still carries real substance in these two fields -- dropping them left
    // the posted PR comment as a bare verdict line with no actual feedback.
    if !verdict.non_blocking_findings.is_empty() {
        out.push_str("\nNon-blocking findings:\n");
        for item in &verdict.non_blocking_findings {
            out.push_str(&format!("- {}\n", item));
        }
    }
    if !verdict.risk_notes.is_empty() {
        out.push_str("\nRisk notes:\n");
        for item in &verdict.risk_notes {
            out.push_str(&format!("- {}\n", item));
        }
    }
    if !verdict.evidence.is_empty() {
        out.push_str("\nEvidence:\n");
        for item in &verdict.evidence {
            out.push_str(&format!("- {}\n", item));
        }
    }
    if !verdict.compatibility_evidence.is_empty() {
        out.push_str("\nCompatibility evidence:\n");
        for item in &verdict.compatibility_evidence {
            out.push_str(&format!("- {}\n", item));
        }
    }
    if let Some(reason) = &verdict.safety_gate_reason {
        out.push_str(&format!("\nGAH safety gate: {reason}\n"));
    }
    out
}

pub(super) fn review_labels(verdict: &ReviewVerdict) -> Vec<&'static str> {
    // TICKET-108: an APPROVE from a weak-tier reviewer, or a low-confidence
    // APPROVE from any reviewer, still needs human eyes -- reviewer identity
    // and the model's self-reported confidence are combined here, not
    // conflated into a single rewritten verdict string.
    let is_weak_tier = verdict.reviewer_tier.as_deref() == Some("weak");
    let is_low_confidence = verdict.confidence == "low";
    // A `HUMAN_REVIEW` text verdict can be a safety-gated APPROVE, an
    // uncertain reviewer, or an actual human handoff. `human_required` is
    // the controller decision after the bounded escalation chain has been
    // considered, so it is the authoritative distinction here.
    if verdict.human_required {
        if is_weak_tier || is_low_confidence {
            return vec!["gah-review-weak", "gah-human-review"];
        }
        return vec!["gah-human-review"];
    }
    match verdict.verdict.as_str() {
        "APPROVE" if is_weak_tier || is_low_confidence => vec!["gah-review-escalating"],
        "APPROVE" => vec!["gah-ready-for-human"],
        "NEEDS_FIX" | "REJECT" => vec!["gah-needs-fix"],
        "HUMAN_REVIEW" => vec!["gah-review-escalating"],
        _ => vec![],
    }
}
